-- Drop the SERVICE_FAULT table
DROP TABLE IF EXISTS SERVICE_FAULT;

-- Drop the FAULT table
DROP TABLE IF EXISTS FAULT;

-- Drop the CATEGORY table
DROP TABLE IF EXISTS CATEGORY;

-- Drop the STAFF_YARD table
DROP TABLE IF EXISTS STAFF_YARD;

-- Drop the YARD table
DROP TABLE IF EXISTS YARD;

-- Drop the HISTORY table
DROP TABLE IF EXISTS HISTORY;

-- Drop the STAFF_ROLE table
DROP TABLE IF EXISTS STAFF_ROLE;

-- Drop the ROLE table
DROP TABLE IF EXISTS ROLE;

-- Drop the STAFF_SERVICE table
DROP TABLE IF EXISTS STAFF_SERVICE;

-- Drop the STAFF table
DROP TABLE IF EXISTS STAFF;

-- Drop the TYPE table
DROP TABLE IF EXISTS TYPE;

-- Drop the SERVICE table
DROP TABLE IF EXISTS SERVICE;

-- Drop the BOAT table
DROP TABLE IF EXISTS BOAT;

-- Drop the CUSTOMER table
DROP TABLE IF EXISTS CUSTOMER;

-- Drop the ADDRESS table
DROP TABLE IF EXISTS ADDRESS;

-- Drop the COUNTRY table
DROP TABLE IF EXISTS COUNTRY;
